# https://github.com/elastic/beats/blob/master/filebeat/filebeat.reference.yml

name: observability-learning
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
  json:
    keys_under_root: true
    add_error_key: true
    message_key: message
    overwrite_keys: true

cloud.id: ""
cloud.auth: ""

logging.level: debug
logging.json: true
logging.selectors: ["*"] 
